name: TPDB backend Qodana Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - development

  pull_request_target:
      types: [opened, synchronize, reopened]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Validate Maven Wrapper
        run: mvn --version


      - name: Run Tests
        run: mvn test


      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: maven-coverage-data
          path: .qodana/code-coverage


      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          pr-mode: false